version: '3.1'

services:
  postgress:
    image: postgres
    restart: always
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:./var/lib/postgresql/data
  # node:
  #   image: node:latest
  #   user: node
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./:/home/node/app
  #   expose:
  #     - "8081"
  #   command: "yarn start"